---
- name: httpd-palvelimen asennus
  hosts: all
  become: true

  pre_tasks:
    - debug:
        msg: “Aloitetaan asennus…”

  roles:
    - httpd_vhost

  post_tasks:
    - debug:
        msg: “…asennus on valmis!”
